name: Download YouTube PiP Extension

on:
  workflow_dispatch:   # run manually
  push:
    branches:
      - main

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - name: Download CRX file
        run: |
          EXT_ID="clngdbkpkpeebahjckkjfobafhncgmne"
          URL="https://clients2.google.com/service/update2/crx?response=redirect&prodversion=91.0&x=id%3D$EXT_ID%26installsource%3Dondemand%26uc"
          curl -L "$URL" -o youtube-pip-extension.crx

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: youtube-pip-extension
          path: youtube-pip-extension.crx
